services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: newsportal-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "NewsPortal@2025"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - newsportal-sql-data:/var/opt/mssql

volumes:
  newsportal-sql-data:
